### ISSUE TITLE
Images don't show anymore :(

### ISSUE THREAD

**Issue by SyphereyD10** [Kazlunn/BDOTimersDocs#8]
**Describe the bug**
All the posts made by the bot (boss reminders, imperial trading, imperial delivery etc ..) no longer have the images, since their source domain is expired :(.
We need to find another way...

**Screenshots**
![image](https://user-images.githubusercontent.com/38891133/128737500-1e2e7ea9-81d0-4496-ae2f-eefe8eb397bb.png)

**Comment by Kazlunn** [comment]
Thanks for letting me know, it should be fixed now! 😄
